list1 = [
    "the", "be", "to", "of", "and", "a", "in", "that", "have", "I", "it", "for", "not", "on", "with",
    "he", "as", "you", "do", "at", "this", "but", "his", "by", "from", "they", "she", "or", "an", "will",
    "my", "one", "all", "would", "there", "their", "what", "so", "up", "out", "if", "about", "who", "get",
    "which", "go", "me", "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
    "people", "into", "year", "your", "good", "some", "could", "them", "see", "other", "than", "then",
    "now", "look", "only", "come", "its", "over", "think", "also", "back", "after", "use", "two", "how",
    "our", "work", "first", "well", "way", "even", "new", "want", "because", "any", "these", "give",
    "day", "most", "us", "is", "are", "was", "were", "had", "been", "has", "said", "says", "did",
    "does", "may", "might", "must", "shall", "should", "could", "would", "will", "can", "find", "found",
    "made", "went", "seen", "came", "got", "gave", "took", "put", "set", "met", "kept", "began",
    "brought", "thought", "fought", "taught", "caught", "bought", "sought", "house", "home", "room", "door",
    "window", "floor", "wall", "street", "city", "town", "country", "world", "land", "water", "river",
    "lake", "sea", "ocean", "mountain", "hill", "tree", "flower", "grass", "leaf", "root", "branch",
    "fruit", "apple", "banana", "orange", "grape", "berry", "nut", "seed", "plant", "animal", "dog",
    "cat", "bird", "fish", "horse", "cow", "pig", "sheep", "goat", "chicken", "egg", "milk", "meat",
    "bread", "rice", "pasta", "cake", "pie", "cookie", "sugar", "salt", "pepper", "oil", "man", "woman",
    "child", "boy", "girl", "father", "mother", "son", "daughter", "brother", "sister", "family", "friend",
    "love", "life", "death", "birth", "marriage", "play", "game", "sport", "ball", "book", "pen",
    "paper", "table", "chair", "bed", "light", "sun", "moon", "star", "sky", "cloud", "rain", "snow",
    "wind", "fire", "earth", "air", "food", "drink", "eat", "sleep", "walk", "run", "jump", "swim",
    "fly", "car", "bus", "train", "plane", "ship", "boat", "road", "path", "bridge", "building", "school",
    "church", "hospital", "store", "market", "money", "gold", "silver", "hour", "minute", "second", "night",
    "morning", "evening", "week", "month", "number", "three", "four", "five", "six", "seven", "eight",
    "nine", "ten", "hundred", "thousand", "million", "big", "small", "long", "short", "high", "low",
    "hot", "cold", "warm", "cool", "wet", "dry", "hard", "soft", "heavy", "light", "strong", "weak",
    "fast", "slow", "old", "young", "beautiful", "ugly", "happy", "sad", "angry", "afraid", "brave",
    "kind", "mean", "rich", "poor", "smart", "stupid", "true", "false", "right", "wrong", "black",
    "white", "red", "blue", "green", "yellow", "purple", "pink", "brown", "gray", "orange", "dark",
    "bright", "clean", "dirty", "full", "empty", "open", "close", "front", "back", "top", "bottom",
    "left", "right", "inside", "outside", "yes", "no", "maybe", "always", "never", "often", "sometimes",
    "soon", "later", "here", "there", "everywhere", "nowhere", "something", "nothing", "everything", "anyone",
    "nobody", "someone", "many", "few", "much", "little", "more", "less", "least", "next", "previous",
    "another", "same", "different", "each", "every", "both", "either", "neither", "through", "during",
    "before", "after", "among", "between", "against", "without", "under", "around", "above", "below",
    "near", "far", "towards", "away", "across", "along", "down", "off", "upon", "onto", "within",
    "outside", "behind", "beside", "beyond", "despite", "except", "including", "until", "since", "whenever",
    "wherever", "however", "therefore", "moreover", "furthermore", "nevertheless", "otherwise", "indeed",
    "namely", "rather", "unless", "although", "though", "even", "while", "once", "as", "if", "that",
    "which", "who", "whom", "whose", "this", "that", "these", "those", "am", "is", "are", "was",
    "were", "be", "been", "being", "have", "has", "had", "having", "do", "does", "did", "will",
    "would", "shall", "should", "may", "might", "must", "can", "could", "go", "went", "gone", "going",
    "come", "came", "see", "saw", "seen", "say", "said", "says", "tell", "told", "know", "knew",
    "known", "think", "thought", "get", "got", "gotten", "give", "gave", "given", "take", "took",
    "taken", "find", "found", "make", "made", "look", "looked", "seem", "seemed", "feel", "felt",
    "try", "tried", "leave", "left", "mean", "meant", "keep", "kept", "let", "begin", "began",
    "begun", "show", "showed", "shown", "hear", "heard", "play", "played", "run", "ran", "stand",
    "stood", "understand", "understood", "watch", "watched", "follow", "followed", "stop", "stopped",
    "create", "created", "speak", "spoke", "spoken", "read", "read", "write", "wrote", "written",
    "drive", "drove", "driven", "buy", "bought", "carry", "carried", "choose", "chose", "chosen",
    "break", "broke", "broken", "spend", "spent", "catch", "caught", "fight", "fought", "teach",
    "taught", "sell", "sold", "learn", "learned", "bring", "brought", "understand", "understood",
    "send", "sent", "grow", "grew", "grown", "draw", "drew", "drawn", "feed", "fed", "hold",
    "held", "eat", "ate", "eaten", "fall", "fell", "fallen", "drink", "drank", "drunk",
    "sing", "sang", "sung", "swim", "swam", "swum", "ring", "rang", "rung", "sit", "sat",
    "set", "sat", "sleep", "slept", "meet", "met", "pay", "paid", "lead", "led", "understand",
    "understood", "win", "won", "fly", "flew", "flown", "cut", "hid", "hidden", "strike", "struck",
    "throw", "threw", "thrown", "wear", "wore", "worn", "choose", "chose", "chosen", "bend", "bent",
    "light", "lit", "shine", "shone", "shoot", "shot", "shut", "shut", "sink", "sank", "sunk",
    "slide", "slid", "slung", "speak", "spoke", "spoken", "speed", "sped", "spend", "spent",
    "spin", "spun", "spit", "spit", "split", "split", "spread", "spread", "spring", "sprang",
    "sprung", "stand", "stood", "steal", "stole", "stolen", "stick", "stuck", "sting", "stung",
    "stink", "stank", "stunk", "stride", "strode", "stridden", "strike", "struck", "stricken",
    "string", "strung", "strive", "strove", "striven", "swear", "swore", "sworn", "sweep", "swept",
    "swim", "swam", "swum", "swing", "swung", "take", "took", "taken", "tear", "tore",
    "torn", "tell", "told", "think", "thought", "thrive", "throve", "thriven", "throw", "threw",
    "thrown", "thrust", "thrust", "tread", "trod", "trodden"
]
list2 = []
str1 = "thecatdogbirdfishrunjumpflyeatdrinkwater"
str2 = ""

for i in range(0, len(str1), 1):
    str2 += str1[i]
    if str2 in list1:
        list2.append(str2)
        str2 = ""
print(list2)

